SCALE = 1
TILE_SIZE = 32
SCREEN_TILE_SIZE = TILE_SIZE * SCALE

SCREEN_WIDTH = 800
SCREEN_HEIGHT = 608

MAPS_DIR = "data/maps"
SPRITES_DIR = "data/sprites"
TILESETS_DIR = "data/tilesets"
TILESETS_INDEX_FILE = "tilesets.txt"
